### ISSUE TITLE
Crashing on iOS

### ISSUE THREAD

**Issue by eddyinet** [hansemannn/titanium-qrcode#2]
Just a heads up that `QRCode.fromString('https://google.com')` crashes on iOS with 11.1.1.GA (Running in Sim on M1). Commenting out the options parsing logic (TiQrcodeModule.swift) resolves. I'll follow-up if I can track the issue down. 👍🏼

**Comment by hansemannn** [comment]
Thanks for the report! Can you file a PR to fix the issue? Thank you!

**Comment by eddyinet** [comment]
Absolutely... once I track it down will do. Would like to retain the options in there as its useful. Thanks Hans.

**Comment by hansemannn** [comment]
I just fixed it and released 4.0.1 for you! Happy coding! https://github.com/hansemannn/titanium-qrcode/releases/tag/ios-4.0.1

**Comment by eddyinet** [comment]
Ha... you're too good. Should've figured it was an easy fix. Thank you sir!
